# This is a basic workflow to help you get started with Actions

name: 'run 52pojie sign'

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: '0 0 * * *' #早上8点执行
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: 安装python3
      run: sudo apt-get update && sudo apt-get install python3 python3-pip python3-bs4 && sudo pip install requests
    
    - name: 在脚本中填入用户参数
      run: |
        sed -i 's/你的server酱SCKEY/${{ secrets.SCKEY }}/' ./BilibiliCheckIn.py
        sed -i 's/你的cookie/${{ secrets.cookie }}/' ./BilibiliCheckIn.py
    - name: 执行签到程序
      run: python3 ./BilibiliCheckIn.py
